### ISSUE TITLE
GitHub Actionsよく使う設定まとめ

### ISSUE THREAD

**Issue by kemu3007** [kemu3007/portal#25]
### 任意のタイミングでテストを回す

pushとpull requestの両方で全てのケースで発火させた場合pull request上で同一の内容のテストが2回発火します。そのためpull requestが作成されたタイミング/pull requestが更新されたタイミング/マージされた(masterにpush)されたタイミングでActionsを発火させます。

```yml
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
```

### 指定した時間帯に処理を回す。

Actionsはcronで回すことができます。`cron: ***` に入れる文字は任意のcronの記法に沿った文字を入力してください。

※ 正確な時間に実行されるのではないので厳密な時刻処理が必要な場合には利用しないでください。

参考: [crontab guru](https://crontab.guru/)

```yml
on:
  schedule:
    - cron:  '0 0 * * *'
```

### キャッシュを保存/利用する(npm)

```yml
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['16']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: portal/package-lock.json
```

<img width="1036" alt="スクリーンショット 2022-03-28 8 20 16" src="https://user-images.githubusercontent.com/29157528/160305562-70f74af2-28ff-4e9a-8737-12919c944cf1.png">
