### ISSUE TITLE
SEOを考えながらSPAをGitHub Pagesにデプロイする

### ISSUE THREAD

**Issue by kemu3007** [kemu3007/portal#44]
summary: GitHub Pages, Cloudflare PagesにサービスにSPAをデプロイする際、SEOの観点から注意しなくてはいけないこと、Angularデプロイのやり方についても説明します。

GitHub Pages, Cloudflare PagesにSPAをデプロイする際、SEOの観点から注意しなくてはいけないこと、Angularデプロイのやり方についても説明します。

#### Build
```bash
$ npm run build
$ cp portal/dist/portal/index.html portal/dist/portal/404.html
```
#### GitHub Actions
```yml
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      ...
      - name: deploy gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./portal/dist/portal
          cname: portal.kemu.site
```

GitHub Pagesは指定されたディレクトリにファイルが存在しない場合、`404.html` を参照します。そのため、`404.html` にも`index.html` を参照するようにします。

### Cloudflare Pages

CloudflareのGitHub連携機能を利用するか、アップロードするActionsが提供されているため利用することになります。

[Cloudflare Pages GitHub Action](https://github.com/marketplace/actions/cloudflare-pages-github-action)

※ `uses: cloudflare/pages-action@1` とサンプルには記載されていますが `uses: cloudflare/pages-action@v1.0.0` と記載しない場合バージョンを見つけられず失敗します。

### ルートディレクトリにしかファイルが存在していないため `blog/` などのパスにアクセスした場合`404` -> `200` という挙動になる。

404が発生する場合Google Search Consoleはそのリンクを不正なリンクと判断し、インデックス登録に失敗してしまいます。

#### 解決策

自前でサーバをホストする場合、nginxのtry_filesを記載することで対応するが、GitHub Pagesなどのマネージドサービスでは設定することができない。そのため全てのURLに対応するディレクトリに `index.html` を配置する。

GoogleBot向けのダミーページを用意し、UserAgentによって振り分けるという手段をこれまで取っていたが管理の煩雑さ、GoogleBotとユーザに与えられる情報の違いはなるべく発生させない方が良いためお勧めできません。

また、最近のGoogleBotはAngularコードを解釈できるChromeのバージョンでレンダリングを行うためできる限りAngularのコードを読ませるべきです。

useHashなどのルータ機能を利用し、 `/#/blog/` といったようなリンクにすることで、404の発生を防ぐことが可能であるが、Googleの検索結果は `#` を含んだURLを正規化してしまうためSEO的には最悪である。

### Twitterに共有した場合TwitterのbotはJSを処理しないためOGPを読んでくれない。

このサイトのようなブログではTwitterの共有時などでOGPを展開してもらえない場合サイトへの流入数が著しく低下してしまう。そのため解決する必要がある。

#### 解決策

OGPの存在する別ページを用意し、Twitter共有リンクをOGP専用ページに向け、OGP専用ページにユーザがアクセスした際は正しいURLに遷移させる。

ツイートボタンの挙動は以下のように記載することで変更できる。

今回は現在のリンクではなく `$/` を先頭につけたリンクがツイート時に表示されるようにする。

```ts
import { Component, AfterViewInit } from '@angular/core';

@Component({
  selector: 'app-tweet-btn',
  template: ` <div style="height: 30px;">
    <a id="btn" href="https://twitter.com/share?ref_src=twsrc%5Etfw" class="twitter-share-button" [attr.data-url]="url"
      >tweet</a
    >
  </div>`,
})
export class TweetBtnComponent implements AfterViewInit {
  ngAfterViewInit(): void {
    const script = document.createElement('script');
    script.async = true;
    script.src = 'https://platform.twitter.com/widgets.js';
    const btn = document.getElementById('btn')!;
    btn.insertAdjacentElement('afterend', script);
  }

  get url() {
    return window.location.origin + '/$' + window.location.pathname + window.location.search;
  }
}
```

主に上記2点がSEO上の問題点です。今後何かSEO的な問題点、改善点についてある場合はまた別の記事にまとめていこうと思います。
