### ISSUE TITLE
Angular Sentryでエラートラッキングを行う

### ISSUE THREAD

**Issue by kemu3007** [kemu3007/portal#48]
summary: Angular ApplicationのエラートラッキングとGitHub Actionsによるソースマップ自動アップロード、リリースの作成を行ったのでやり方を紹介します。

## Introduction

```bash
$ npm i @sentry/angular @sentry/tracing
```

## environment

開発環境でエラートラッキングは行わないため `environment.prod.ts` にのみDSNを記載。
DSNは `Settings > Projects > Client Keys` で取得できます。

- environment.ts

```ts
export const environment: Env = {
  sentryDSN: '',
};

```
- environment.prod.ts

```ts
export const environment: Env = {
  sentryDSN: '****************************',
};
```

## main.ts

tracesSampleRateを減らすことで同じエラーが送られる回数を減らすことができます。

1.0: 全てのエラーをSentryに送信

```ts
import * as Sentry from '@sentry/angular';
import { BrowserTracing } from '@sentry/tracing';

Sentry.init({
  dsn: environment.sentryDSN,
  integrations: [
    new BrowserTracing({
      tracingOrigins: ['localhost', 'https://portal.kemu.site'],
      routingInstrumentation: Sentry.routingInstrumentation,
    }),
  ],
  tracesSampleRate: 1.0,
});

if (environment.production) {
  enableProdMode();
}

platformBrowserDynamic()
  .bootstrapModule(AppModule)
  .catch((err) => console.error(err));
```

## app.module.ts

showDialogはtrueにすることでエラー発生時にフォームダイアログを起動し、ユーザにクラッシュデータを送信してもらうことができます。

```ts
import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';
import { APP_INITIALIZER, ErrorHandler, NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { Router } from '@angular/router';
import * as Sentry from '@sentry/angular';

@NgModule({
  declarations: [AppComponent],
  imports: [BrowserModule, AppRoutingModule],
  providers: [
    { provide: ErrorHandler, useValue: Sentry.createErrorHandler({ showDialog: false }) },
    { provide: Sentry.TraceService, deps: [Router] },
    { provide: APP_INITIALIZER, useFactory: () => () => {}, deps: [Sentry.TraceService], multi: true },
  ],
  bootstrap: [AppComponent],
})
export class AppModule {}
```

これでエラーがSentryに通知されるようになります。

Sentryへの通知をテストする場合は任意の箇所に `throw new Error('test exception!');` を仕込めばOKです。
 
## SourceMapの作成

Angularはbuild時に難読化されるため、Sentry上からエラー内容が分かりづらくなります。そのため、build時にソースマップを生成し、Sentryに入力します。

- SourceMapの作成

```bash
$ npm run build -- --sourceMap=true
```

GitHub Actionsのワークフローを利用してアップロードします。

https://github.com/marketplace/actions/sentry-release

この際、Sentry側でトークンを発行する必要があります。

Settings > Developer Settings > Create New Integration > Internal Integration

権限を以下のように設定し、トークンをGitHub Secretsに `SENTRY_AUTH_TOKEN` として登録します。

![image](https://user-images.githubusercontent.com/29157528/170847335-d3c22049-f20d-401a-84ed-3c6b0f7f785c.png)

また、`SENTRY_ORG`,  `SENTRY_PROJECT` についても同様に設定します。

SENTRY_ORG: `Settings > General Settings > Organization Slug` 
SENTRY_PROJECT: `Settings > Projects > Name` 

- deploy.yml

```yml
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['16']
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: install deps
        run: |
          npm install
      - name: build
        run: |
          npm run ng build -- --sourceMap=true |& tee -a $GITHUB_STEP_SUMMARY
      - uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          sourcemaps: './dict/'
```

fetch-depthを設定しない場合エラーになります。デフォルトで1つのコミットしか取得しないのでSentryにアップロードする時にバージョンタグの作成でコケる様子。(set_commitsをskipにしてもエラーを回避できます。)

## 終わりに

上記ステップで無事、Sentry自動リリースフローを作成することができました。最近はなんでもGitHub Actions Workflowを用意してくれていてとても便利だなあと感じています。
