### ISSUE TITLE
GitHub Actions 小技 (1)

### ISSUE THREAD

**Issue by kemu3007** [kemu3007/portal#54]
summary: 複数回Pushした際の前のJobの自動キャンセル、Job Summaryへの情報書き込み方を紹介します。

## Job自動キャンセル

concurrencyを利用します。

concurrency: https://docs.github.com/ja/actions/using-jobs/using-concurrency

```yml
name: deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency: 
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
      ...
```

これにより以下のように前のJOBが自動でキャンセルされます。

![image](https://user-images.githubusercontent.com/29157528/172042149-7d0173d8-c4fa-432d-8a6b-8523f1687196.png)

## Job Summaryへの情報書き込み

`$GITHUB_STEP_SUMMARY` を利用します。

```yml
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: portal/package-lock.json
      - name: install deps
        working-directory: ./portal
        run: |
          npm install
      - name: build
        working-directory: ./portal
        run: |
          npm run compodoc
          npm run ng build -- --sourceMap=true |& tee -a $GITHUB_STEP_SUMMARY
```

teeコマンドを利用し、ビルド時のログを `$GITHUB_STEP_SUMMARY` に書き出すようにしています。

以下のように表示されます。

![image](https://user-images.githubusercontent.com/29157528/172042241-56442f63-e154-427c-ae70-73e4426371ce.png)
