### ISSUE TITLE
AWS CodePipelineとGitHubを連携させてECRにイメージをPushする

### ISSUE THREAD

**Issue by kemu3007** [kemu3007/portal#55]
summary: GitHubのOAuth認証を利用しAWS CodePipelineと連携させ、トリガされたCodeBuildを用いたECRへのAuto Pushを行ったのでやり方を紹介します。

GitHubのOAuth認証を利用し、CodePipelineと連携、CodeBuildを用いたECRへのAuto Pushを行ったのでやり方を紹介します。

OAuth認証を利用することで、デベロッパーはAWSへのトークンを手動で管理する必要がなくなり、CodeBuild以降の権限管理はAWSのフレームワークを利用できるため完全にトークンレスになります。

## GitHubとAWS CodePipeline連携

OAuth認証を利用します。

`CodePipeline > 接続 > 接続を作成` から連携を作成することができます。

![image](https://user-images.githubusercontent.com/29157528/173198376-c5593755-f6a8-45d3-a084-0b0aa54b9727.png)

## Elastic Container Registory, CodeBuildの用意

CodePipelineの設定に必要になるため、先にECRの初期設定、CodeBuildの作成を行います。

### Elastic Container Registory

`Amazon ECR > レポジトリを作成` からレポジトリを作成します。今回はPrivateイメージを想定します。

summary: GitHubのOAuth認証を利用しAWS CodePipelineと連携させ、トリガされたCodeBuildを用いたECRへのAuto Pushを行ったのでやり方を紹介します。

GitHubのOAuth認証を利用し、CodePipelineと連携、CodeBuildを用いたECRへのAuto Pushを行ったのでやり方を紹介します。

## GitHubとAWS CodePipeline連携

OAuth認証を利用します。

`CodePipeline > 接続 > 接続を作成` から連携を作成することができます。

![image](https://user-images.githubusercontent.com/29157528/173198376-c5593755-f6a8-45d3-a084-0b0aa54b9727.png)

## Elastic Container Registory, CodeBuildの用意

CodePipelineの設定に必要になるため、先にECRの初期設定、CodeBuildの作成を行います。

### Elastic Container Registory

`Amazon ECR > レポジトリを作成` からレポジトリを作成します。今回はPrivateイメージを想定します。

![image](https://user-images.githubusercontent.com/29157528/173199828-f633c796-47b1-4c37-82ea-bb1d7ae18540.png)

### CodeBuildの設定

`CodeBuild > プロジェクトの作成`

今回はDockerイメージの構築を行うため、特権付与を行います。また、buildspecファイルを利用する形にしてください。
その他、イメージ, ログの管理などに関しては好きなように設定してOKです。

![image](https://user-images.githubusercontent.com/29157528/173199385-9857e08e-2158-4292-8ee2-b501d8a5a7b5.png)
## CodePipelineの作成

`CodePipeline　> パイプラインを作成する`

![image](https://user-images.githubusercontent.com/29157528/173198769-407d678d-3523-4232-9170-a142b456f062.png)
![image](https://user-images.githubusercontent.com/29157528/173198785-a516c306-894c-4251-acb5-df134830d5a6.png)

先ほど作成した接続に基づいて、利用するレポジトリ、リリースを行うブランチについて選択します。

### CodeBuildの設定

`CodeBuild > プロジェクトの作成`

今回はDockerイメージの構築を行うため、特権付与を行います。また、buildspecファイルを利用する形にしてください。
その他、イメージ, ログの管理などに関しては好きなように設定してOKです。

![image](https://user-images.githubusercontent.com/29157528/173199385-9857e08e-2158-4292-8ee2-b501d8a5a7b5.png)

## IAMの設定を行う

`IAM > ロール > codebuild-*****`

CodeBuildで作成した/利用しているロールにECRへの権限を付与する必要があります。

今回の動作確認では`アクセス許可を追加 > ポリシーをアタッチ` からAmazonEC2ContainerRegistryFullAccessを付与しました。

## CodePipelineの作成

`CodePipeline　> パイプラインを作成する`

![image](https://user-images.githubusercontent.com/29157528/173198769-407d678d-3523-4232-9170-a142b456f062.png)
![image](https://user-images.githubusercontent.com/29157528/173198785-a516c306-894c-4251-acb5-df134830d5a6.png)

先ほど作成した接続, CodeBuild, ECRに基づいて、利用するレポジトリ、リリースを行うブランチについて選択します。

デプロイステップに関しては今回スキップします。

## buildspec.yml

buildspec.ymlを以下のような形で作成し、レポジトリ配下に作成します。

```yml
version: 0.2
phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 535811171857.dkr.ecr.ap-northeast-1.amazonaws.com
  build:
    commands:
      - docker build -t container-image . 
  post_build:
    commands:
      - docker tag kemu-site *****.dkr.ecr.ap-northeast-1.amazonaws.com/container-image:latest
      - docker tag kemu-site *****.dkr.ecr.ap-northeast-1.amazonaws.com/container-image:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - docker push -a 535811171857.dkr.ecr.ap-northeast-1.amazonaws.com/container-image
```

`$CODEBUILD_RESOLVED_SOURCE_VERSION` などの利用可能な環境変数は以下のページから確認できます。

[ビルド環境の環境変数](https://docs.aws.amazon.com/ja_jp/codebuild/latest/userguide/build-env-ref-env-vars.html)

上記設定によりECRにAuto Pushされます。次回はPushしたECRイメージからECSへのデプロイを行います。
