### ISSUE TITLE
pipeを利用した場合のexitステータスの取り扱い

### ISSUE THREAD

**Issue by kemu3007** [kemu3007/portal#61]
summary: pipeを利用してコマンドの実行結果を別ファイルに書き出すなどの手法を取る際、pipeを利用する前のexitステータスコードが必要になるケースが存在します。その際のexitステータスの取り扱い方について紹介します。

pipeを利用してコマンドの実行結果を別ファイルに書き出すなどの手法を取る際、pipeを利用する前のexitステータスコードが必要になるケースが存在します。その際のexitステータスの取り扱い方について紹介します。

bashのケースを元に解説しているのでzshの場合は `$PIPESTATUS` -> `$pipestatus` に変更してください。

## bad 

以下のコマンドのステータス返り値は0になります。

```bash
$ exit 1 |& tee -a $GITHUB_STEP_SUMMARY 
```

これはteeコマンドの返却したステータスを読み取ってしまっていることに起因しています。

## good

pipeで実行結果を渡し、一つ目のコマンドの実行結果いかんによってコマンドを失敗させる場合は以下のように書きましょう。

```bash
exit 1 |& tee -a $GITHUB_STEP_SUMMARY
exit ${PIPESTATUS[0]}
```

### .github/workflows/exit_pipe_test.yml

```yml
name: exit_pipe_test

on:
  workflow_dispatch:

jobs:
  test_1:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          exit 1 |& tee -a $GITHUB_STEP_SUMMARY
  test_2:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          exit 1 |& tee -a $GITHUB_STEP_SUMMARY
          exit ${PIPESTATUS[0]}
```

### 実行結果

![image](https://user-images.githubusercontent.com/29157528/177806990-df4278cb-1014-4be9-9467-97da878fedc3.png)
